### ISSUE TITLE
MAJOR BUG

### ISSUE THREAD

**Issue by Super45coder** [Educational-Websites/HTML-tutorials#2]
There is a issue. The buttons are not green. @Genius398 @somePythonProgrammer @Sreehari521 @e-coders

**Comment by Super45coder** [comment]
Okay.

**Comment by Genius398** [comment]
@Super45coder for the css i suggest making branches and pull requests to update it so that we can reverse a change is needed

**Comment by Super45coder** [comment]
Yes. Nice idea. Updating style.css
________________________________

**Comment by Super45coder** [comment]
Finished with updating style.css. Made first wiki.
________________________________

**Comment by Genius398** [comment]
ok i'll help

**Comment by Super45coder** [comment]
Thanks! And check out the wiki
________________________________

**Comment by Genius398** [comment]
@Genius398 @Super45coder the bug. I tried to fix unsuccessfully

**Comment by Super45coder** [comment]
Its okay. I will try.
________________________________

**Comment by Genius398** [comment]
@Super45coder i updated the license

**Comment by Genius398** [comment]
@Super45coder YAYYYYY YOOOOOOHOOOOOO

**Comment by Genius398** [comment]
one more to go

**Comment by Genius398** [comment]
im getting it back online

**Comment by Super45coder** [comment]
Yes! Nice job!
________________________________
