### ISSUE TITLE
HUGE ISSUE WITH ORDER

### ISSUE THREAD

**Issue by Super45coder** [Educational-Websites/HTML-tutorials#37]
Here is how to get to the bug. 
1: Go to code section
2: Go to link

The order is completely messed up. Please fix!

**Comment by Genius398** [comment]
Fixed

**Comment by Genius398** [comment]
no

**Comment by Super45coder** [comment]
Okay.

**Comment by Super45coder** [comment]
Great! Thanks! HTML tutorials is done. Please make the copyright page. And I invited you to a new organization called Journ 12 Journals
________________________________

**Comment by e-coders** [comment]
Ok!
